EC_HOME=$HOME/enginecloud
SSH_USER=$USER
STOCKFISH_VERSION=stockfish_14.1_linux_x64_bmi2

GCP_PROJECT=
GCP_ZONE=
GCP_MACHINE_TYPE=
GCP_IMAGE_PROJECT=debian-cloud
GCP_IMAGE_FAMILY=debian-10
GCP_INSTANCE_NAME=stockfish
